In [7]:
import numpy as np
from sklearn import datasets, metrics
from sklearn.datasets import load_iris 
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB 
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report  # <-- FIXED HERE

# Load data
iris = datasets.load_iris()
X = iris.data
y = iris.target

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# Train model
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)

# Predict
y_pred = nb_classifier.predict(X_test)

# Evaluate
acc = accuracy_score(y_test, y_pred)
print(acc)
print(f"Accuracy: {acc*100:.2f}%")




1.0
Accuracy: 100.00%


In [8]:
res = confusion_matrix(y_test,y_pred)
print(res)

[[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]


In [9]:
res1 = classification_report(y_test,y_pred)
print(res1)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

